#32位随机数
roncoo: 
  secret: ${random.value}
  number: ${random.int}
  name: www.baidu.com
  descr: ${roncoo.name} is a new site
 
server: 
  port: 8080

#主配置文件，配置了这个会优先读取里面的属性覆盖主配置文件的属性
spring: 
#时间格式化
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
#时区设置
    time-zone: Asia/Chongqing
  profiles: 
    active: test
---
spring: 
  profiles: dev
#会覆盖住配置文件的参数
server: 
  port: 8087
---
spring: 
  profiles: test
#会覆盖住配置文件的参数
server: 
  port: 8085
---
spring: 
  profiles: prod
#会覆盖住配置文件的参数
server: 
  port: 8089

