#32位随机数
roncoo: 
  secret: ${random.value}
  number: ${random.int}
  name: www.baidu.com
  descr: ${roncoo.name} is a site you can try it

server: 
  port: 8090

#时间格式化
spring: 
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
#时区设置
    time-zone: Asia/Chongqing